version: '3' 
services: 
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   command: redis-server --port 6379
  #   container_name: redis_boot
  #   hostname: redis_boot
  #   labels:
  #     - "name=redis"
  #     - "mode=standalone"
  #   ports:
  #     - "6379:6379"

  mongodb: 
    image: mongo 
    ports: 
      - "${MONGO_PORT}:27017"
    volumes: 
      - ./data/db:/data/db 
    container_name: "docker-mongodb" 
    env_file: 
      - .env